version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.14.3-jessie

    steps:
      - checkout
      - run:
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN;
      - restore_cache:
          key: base-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: example-cache-{{ checksum "package.json" }}
      - run:
          command: npm install && cd example && npm install
      - save_cache:
            key: base-cache-{{ checksum "package.json" }}
            paths:
              - node_modules
      - save_cache:
            key: example-cache-{{ checksum "example/package.json" }}
            paths:
              - example/node_modules
  test:
    docker:
      - image: circleci/node:6.14.3-jessie

    steps:
      - checkout
      - restore_cache:
          key: base-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: example-cache-{{ checksum "example/package.json" }}
      - run:
          command: npm run gulp -- ava
      - run:
          command: npm run gulp -- eslint
      - run:
          command: cd example && npm run gulp -- default
      - run:
          command: sleep 10 && curl --retry 10 --retry-delay 5 -v http://localhost:3000/

  publish:
    docker:
      - image: circleci/node:6.14.3-jessie

    steps:
      - checkout
      - restore_cache:
          key: base-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: example-cache-{{ checksum "example/package.json" }}
      - run:
          command: ./publish


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - test
